"""initial models

Revision ID: c3d87bb08504
Revises: 
Create Date: 2026-03-19 13:57:09.613437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d87bb08504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performer_type', sa.String(length=100), nullable=True),
    sa.Column('subject_type', sa.String(length=100), nullable=True),
    sa.Column('timing_type', sa.String(length=20), nullable=True),
    sa.Column('timing_frequency', sa.Integer(), nullable=True),
    sa.Column('timing_period', sa.Float(), nullable=True),
    sa.Column('timing_period_unit', sa.String(length=10), nullable=True),
    sa.Column('timing_duration', sa.Float(), nullable=True),
    sa.Column('timing_duration_unit', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('canonical_libs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('canonical_lib_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_lib_display_text', sa.String(length=500), nullable=True),
    sa.Column('canonical_lib_url', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_lib_name'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('concept_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('concept_type_name', sa.String(length=255), nullable=False),
    sa.Column('concept_type_display_text', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_type_name'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('intended_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('intended_use_name', sa.String(length=255), nullable=False),
    sa.Column('intended_use_display_text', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('intended_use_name')
    )
    op.create_table('plan_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('fhir_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('subject_type', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('usage', sa.Text(), nullable=True),
    sa.Column('copyright', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('editor', sa.String(length=500), nullable=True),
    sa.Column('reviewer', sa.String(length=500), nullable=True),
    sa.Column('endorser', sa.String(length=500), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('effective_period_start', sa.Date(), nullable=True),
    sa.Column('effective_period_end', sa.Date(), nullable=True),
    sa.Column('validity_duration', sa.String(length=50), nullable=True),
    sa.Column('related_artifact', sa.Text(), nullable=True),
    sa.Column('library', sa.String(length=500), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('fhir_data', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('plandef_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('plandef_type_name', sa.String(length=255), nullable=False),
    sa.Column('plandef_type_display_text', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('plandef_type_name')
    )
    op.create_table('response_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('response_type_name', sa.String(length=255), nullable=False),
    sa.Column('response_type_display_text', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('response_type_name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('unit_display_text', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('unit_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plandefinition_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plandefinition_guid', sa.String(length=36), nullable=False),
    sa.Column('activity_guid', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_guid'], ['activities.guid'], ),
    sa.ForeignKeyConstraint(['plandefinition_guid'], ['plan_definitions.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plandefinition_guid', 'activity_guid', name='uq_plandef_activity')
    )
    op.create_table('values_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('canonical_lib', sa.String(length=36), nullable=False),
    sa.Column('canonical_refnumber', sa.String(length=255), nullable=True),
    sa.Column('value_name', sa.String(length=255), nullable=False),
    sa.Column('value_display_text', sa.String(length=500), nullable=True),
    sa.Column('value_explanation', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_lib'], ['canonical_libs.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('valuesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('canonical_lib', sa.String(length=36), nullable=False),
    sa.Column('canonical_refnumber', sa.String(length=255), nullable=True),
    sa.Column('valueset_name', sa.String(length=255), nullable=False),
    sa.Column('valueset_display_text', sa.String(length=500), nullable=True),
    sa.Column('valueset_explanation', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_lib'], ['canonical_libs.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('valueset_name')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('canonical_lib', sa.String(length=36), nullable=False),
    sa.Column('canonical_refnumber', sa.String(length=255), nullable=True),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('concept_display_text', sa.String(length=500), nullable=True),
    sa.Column('concept_explain', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('concept_type', sa.String(length=36), nullable=True),
    sa.Column('response_type', sa.String(length=36), nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('range_low', sa.Float(), nullable=True),
    sa.Column('range_high', sa.Float(), nullable=True),
    sa.Column('anchor_low_text', sa.String(length=255), nullable=True),
    sa.Column('anchor_high_text', sa.String(length=255), nullable=True),
    sa.Column('valueset', sa.String(length=36), nullable=True),
    sa.Column('no_of_values_connected', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('vers_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_valid', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(range_low IS NULL OR range_high IS NULL OR range_low <= range_high)', name='ck_concept_range'),
    sa.ForeignKeyConstraint(['canonical_lib'], ['canonical_libs.guid'], ),
    sa.ForeignKeyConstraint(['concept_type'], ['concept_types.guid'], ),
    sa.ForeignKeyConstraint(['response_type'], ['response_types.guid'], ),
    sa.ForeignKeyConstraint(['unit'], ['units.guid'], ),
    sa.ForeignKeyConstraint(['valueset'], ['valuesets.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('valueset_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valueset_guid', sa.String(length=36), nullable=False),
    sa.Column('value_guid', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['value_guid'], ['values_catalog.guid'], ),
    sa.ForeignKeyConstraint(['valueset_guid'], ['valuesets.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valueset_guid', 'value_guid', name='uq_valueset_value')
    )
    op.create_table('plandefinition_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('plandefinition_guid', sa.String(length=36), nullable=False),
    sa.Column('concept_guid', sa.String(length=36), nullable=True),
    sa.Column('concept_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_quantity', sa.Float(), nullable=True),
    sa.Column('target_operator', sa.String(length=10), nullable=True),
    sa.Column('target_range_low', sa.Float(), nullable=True),
    sa.Column('target_range_high', sa.Float(), nullable=True),
    sa.Column('target_categorical_text', sa.String(length=500), nullable=True),
    sa.Column('target_value_guid', sa.String(length=36), nullable=True),
    sa.Column('target_unit', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_guid'], ['concepts.guid'], ),
    sa.ForeignKeyConstraint(['plandefinition_guid'], ['plan_definitions.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('activity_guid', sa.String(length=36), nullable=False),
    sa.Column('concept_guid', sa.String(length=36), nullable=True),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('range_min', sa.Float(), nullable=True),
    sa.Column('range_max', sa.Float(), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_guid'], ['activities.guid'], ),
    sa.ForeignKeyConstraint(['concept_guid'], ['concepts.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('plandefinition_goals')
    op.drop_table('valueset_values')
    op.drop_table('concepts')
    op.drop_table('valuesets')
    op.drop_table('values_catalog')
    op.drop_table('plandefinition_activities')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('response_types')
    op.drop_table('plandef_types')
    op.drop_table('plan_definitions')
    op.drop_table('intended_uses')
    op.drop_table('concept_types')
    op.drop_table('canonical_libs')
    op.drop_table('activities')
    # ### end Alembic commands ###
