"""Add forms tables: questionnaires, questionnaire_items, questionnaire_responses

Revision ID: dcc76e2d3060
Revises: c3d87bb08504
Create Date: 2026-03-23 08:01:52.447699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc76e2d3060'
down_revision = 'c3d87bb08504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_guid', sa.String(length=36), nullable=False),
    sa.Column('form_guid', sa.String(length=36), nullable=False),
    sa.Column('form_version', sa.Integer(), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('fhir_json', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_guid')
    )
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_form_guid'), ['form_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_guid', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fhir_json', sa.JSON(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('production_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_guid', 'version', name='uq_form_guid_version')
    )
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaires_content_fingerprint'), ['content_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaires_form_guid'), ['form_guid'], unique=False)

    op.create_table('questionnaire_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('form_guid', sa.String(length=36), nullable=False),
    sa.Column('form_version', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('default_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_items_form_guid'), ['form_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_items_form_guid'))

    op.drop_table('questionnaire_items')
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaires_form_guid'))
        batch_op.drop_index(batch_op.f('ix_questionnaires_content_fingerprint'))

    op.drop_table('questionnaires')
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_form_guid'))

    op.drop_table('questionnaire_responses')
    # ### end Alembic commands ###
